[cursor.style]
shape    = "Beam"
blinking = "On"

#region bug fix
[[keyboard.bindings]]
key   = "Backspace"
chars = "\u007f"

[[keyboard.bindings]]
key   = "Backspace"
mods  = "Control"
chars = "\b"
#endregion

[[keyboard.bindings]]
key    = "n"
mods   = "Control|Shift"
action = "CreateNewWindow"

[[keyboard.bindings]]
key    = "F11"
action = "ToggleFullscreen"

[[mouse.bindings]]
mouse  = "Right"
action = "Paste"

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[terminal]
shell = "pwsh"

[window]
resize_increments = true

[window.dimensions]
columns = 120
lines   = 35

[bell]
animation = "EaseOut"
color     = "#111111"
duration  = 216

[font]
normal.family = "0xProto Nerd Font Mono"
size = 12

[general]
import = ["./theme_dark.toml"]
working_directory = "C:\\Users\\cmema"
